#!/bin/bash

APP_DIR="$(cd "$(dirname "$0")/../../.." && pwd)"

osascript <<EOF
tell application "Terminal"
    activate
    do script "cd '$APP_DIR'; java -jar launcher.jar; echo 'Process finished. Press Enter to close.'; read -n 1"
end tell
EOF